trigger:
  tags:
    include:
     - v*
pr: none

variables:
  BuildParameters.mavenPOMFile: 'pom.xml'
  name: $(date:yyyyMMdd)$(rev:.r)
  TAGS: ''
  TAG: ''

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:

    - script: |
        echo "##vso[task.setvariable variable=TAGS]$(git tag --sort=-creatordate)"
        echo "##vso[task.setvariable variable=TAG]$TAGS[0]"
      displayName: Set maven version

    - script: |
        echo "$(TAGS)"
        echo "$(TAG)"
      displayName: Set maven version
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          $tags = git tag --sort=-creatordate
          $tag = $tags[0]
          echo$(tag)