schedules:
  - cron: '52 9 * * *'
    displayName: Daily midnight build
    branches:
      include:
      - master
    always: true

trigger: none

pr: none

variables:
  BuildParameters.mavenPOMFile: 'pom.xml'
  name: $(date:yyyyMMdd)$(rev:.r)
  TAGS: ''
  TAG: ''
  CARBON_APIMGT_TAG_APIM: ''

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:

    # - script: |
    #     echo "#####1"
    #     mapfile -t sortedTagList < <(git tag --sort=-creatordate )
    #     echo "#####2"
    #     echo "##vso[task.setvariable variable=CARBON_APIMGT_TAG_APIM]${sortedTagList[0]}"
    #     echo "#####3"
    #     echo ${sortedTagList[0]}
    #     echo "#####4"
    #   displayName: Set maven version

    - script: |
        git describe --abbrev=0
        # echo "##vso[task.setvariable variable=CARBON_APIMGT_TAG_APIM]$(echo $(Build.SourceBranch) | sed 's|.*/||')"
        echo "##vso[task.setvariable variable=CARBON_APIMGT_TAG_APIM]$(git describe --abbrev=0)"
      displayName: Set maven version
    
    - script: |
        echo "CARBON_APIMGT_TAG_APIM: $(CARBON_APIMGT_TAG_APIM)"
      displayName: Set maven version
