variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
name: $(date:yyyyMMdd)$(rev:.r)

pr:
  branches:
    include:
    - testBranch
    - master

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
    
  steps:
  - task: CmdLine@2
    displayName: Create artifact from variables
    inputs:
      script: |
        echo "##vso[task.setvariable variable=FOO;]$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" >  $(Build.ArtifactStagingDirectory)/pipeline.env
        
  - bash: |
        echo $SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
        echo $SYSTEM_PULLREQUEST_PULLREQUESTID
        echo This is a simple echo message for successful build.


   
...
