trigger:
  tags:
    include:
     - v*
pr: none

variables:
  BuildParameters.mavenPOMFile: 'pom.xml'
  name: $(date:yyyyMMdd)$(rev:.r)


stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:

    - script: |
        $tags=git tag --sort=-creatordate
        $tag=$tags[0]
      displayName: Set maven version