pr:
  branches:
    include:
    - master

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
    
  steps:
  - task: CmdLine@2
    displayName: Create artifact from variables
    inputs:
      script: |
        echo "This is a simple message"
        echo "##vso[task.logissue type=error]Something went very wrong."
        echo "##vso[task.setvariable variable=testvar;]testvalue"
        echo $testvar
        echo "##vso[task.setvariable variable=FOO1;]ABCD"
        echo $FOO1
        echo "##vso[task.setvariable variable=FOO;]$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" >  $(Build.ArtifactStagingDirectory)/pipeline.env
        echo $FOO
  - task: PublishBuildArtifacts@1
    displayName: publish variables
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'variables'
      publishLocation: 'Container'


  # - bash: |
  #       echo $SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
  #       echo $SYSTEM_PULLREQUEST_PULLREQUESTID
  #       echo This is a simple echo message for successful build.
