
pr:
  branches:
    include:
    - master

jobs:
- job: main
  steps:
  - script: echo "##vso[task.setvariable variable=FOO;isOutput=true]"$[SYSTEM_PULLREQUEST_PULLREQUESTNUMBER]
    displayName: Set output variables
    name: myEnv
- job: variables_handler
  dependsOn: main
  variables: 
    FOO: $[ dependencies.main.outputs['myEnv.FOO'] ]
  steps:
  - task: CmdLine@2
    displayName: Create artifact from variables
    inputs:
      script: |
        echo "##vso[task.setvariable variable=FOO;]$(FOO)" >  $(Build.ArtifactStagingDirectory)/pipeline.env
  - task: PublishBuildArtifacts@1
    displayName: publish variables
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'variables'
      publishLocation: 'Container'

  - script: |
        $SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
        $SYSTEM_PULLREQUEST_PULLREQUESTID
        echo $env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
        echo $env:SYSTEM_PULLREQUEST_PULLREQUESTID
        $env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER
        $env:SYSTEM_PULLREQUEST_PULLREQUESTID
        echo $[SYSTEM_PULLREQUEST_PULLREQUESTNUMBER]
        echo $[SYSTEM_PULLREQUEST_PULLREQUESTID]
        echo $(SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)
        echo $(SYSTEM_PULLREQUEST_PULLREQUESTID)
        echo This is a simple echo message for successful build.
